### ISSUE TITLE
Feature request: customize colors

### ISSUE THREAD

**Issue by chadhs** [raugturi/powerline-evil#2]
would love to be able to customize the colors of powerline-evil-vim-color-theme to match solarized color scheme.  :-)

**Comment by raugturi** [comment]
There are faces for each mode that can be used to set those. Each mode's face is powerline-evil-<mode>-face, so powerline-evil-normal-face, powerline-evil-insert-face, etc. You can set those in your init to override the defaults. The defaults mode colors are:

* base: white
* normal: green
* insert: blue
* visual: orange
* operator: cyan
* replace: red
* motion: magenta
* emacs: violet

I used to have a snippet from my init mapping them to solarized colors, but I can't find it now and I don't even use Emacs anymore.

**Comment by chadhs** [comment]
really newbie question…

@raugturi how do i set those values?

trying something like this so far.
```
(powerline-evil-vim-color-theme)
(set-face-attribute 'powerline-evil-normal-face "blue")
```

**Comment by chadhs** [comment]
got it!

```lisp
;;; emacs powerline
(require 'powerline-evil)
(powerline-evil-vim-color-theme)
(custom-set-faces
 '(powerline-evil-normal-face ((t (:background "#859900" :foreground "#eee8d5"))))
 '(powerline-evil-insert-face ((t (:background "#268bd2" :foreground "#eee8d5"))))
 '(powerline-evil-visual-face ((t (:background "#cb4b16" :foreground "#eee8d5"))))
 '(powerline-evil-operator-face ((t (:background "#2aa198" :foreground "#eee8d5"))))
 '(powerline-evil-replace-face ((t (:background "#dc322f" :foreground "#eee8d5"))))
 '(powerline-evil-motion-face ((t (:background "#d33682" :foreground "#eee8d5"))))
 '(powerline-evil-emacs-face ((t (:background "#6c71c4" :foreground "#eee8d5"))))
 )
```
