### ISSUE TITLE
How to show window number, when i am using "window numbering" 

### ISSUE THREAD

**Issue by nasoundead** [raugturi/powerline-evil#3]
I use "window numbering" to move between windows, but the "powerline-evil" doesn't show the number. It make me sad.

**Comment by raugturi** [comment]
I'm not familiar with that feature. I stopped using emacs a while ago. If you are referring to this: https://github.com/nschum/window-numbering.el it looks like you could make a new theme with `(window-numbering-mode)` in it and that should display it. If that doesn't work let me know and I'll see if I can figure out how you would go about adding it.

**Comment by raugturi** [comment]
Did that solve the problem?
